name: chat
description: A new Flutter project.
publish_to: none
version: 2.0.5+205
environment:
  sdk: ^3.5.0
dependencies:
  dio: ^5.6.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  gap: ^3.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  event_bus: ^2.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  crop_image: ^1.0.13
  vibration: ^2.0.0
  flutter_linear_datepicker: ^2.0.6
  shamsi_date: ^1.0.4
  path: ^1.9.0
  device_info_plus: ^10.1.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  fl_chart: ^0.69.0
  awesome_notifications: ^0.9.3+1
  timeago: ^3.7.0
  emoji_picker_flutter: ^4.3.0
  file_picker: ^8.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cache: ^1.5.1
  dio_cache_interceptor: ^3.5.0
  screenshot: ^3.0.0
  bubble: ^1.2.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  video_player: ^2.9.2
  flutter_audio_waveforms: ^1.2.1+8
  waveform_extractor: 1.1.3
  record: ^5.2.0
  video_player_control_panel: ^1.1.2
  glass: ^2.0.0+1
  socket_io_client: ^3.0.1
  objectid: ^3.1.0
  vector_map_tiles: ^8.0.0
  restart_app: ^1.3.2
  flutter_inappwebview:
    path: ./packages/flutter_inappwebview/flutter_inappwebview
  flutter_image_compress: ^2.4.0
  firebase_messaging: 15.1.6
  firebase_crashlytics: 4.2.0
  firebase_core: 3.9.0
  firebase_analytics: 11.3.6
  flutter_markdown: ^0.7.6+2
  flutter_html_v3: ^3.0.6
  sms_autofill: ^2.4.1
  livekit_client: ^2.3.1+hotfix.1
  js: ^0.7.1
  flutter_poolakey:
    path: ./lib/flavors/cafebazaar/flutter_poolakey
  wakelock_plus: ^1.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.12
  rename_app: ^1.6.1
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  fonts:
    - family: YekanBakh
      fonts:
        - asset: lib/assets/fonts/YekanBakhFaNum-Regular.ttf
    # - family: NotoColorEmoji
    #   fonts:
    #     - asset: lib/assets/fonts/NotoColorEmoji-Regular.ttf
  assets:
    - lib/assets/images/empty.png
    - lib/assets/images/confetti.png
    - lib/app/assets/images/splash_logo.png
    - lib/app/assets/images/auth_logo.png
    - lib/app/assets/images/auth_hero.png
    - lib/app/assets/images/star.png
    - lib/app/assets/images/fire.png
    - lib/app/assets/images/map_marker.png
    - lib/app/assets/images/logo-white.png
    - lib/app/assets/images/pattern.png
    - lib/app/assets/images/one.png
    - lib/app/assets/images/two.png
    - lib/app/assets/images/three.png
    - lib/app/assets/images/cafebazaar.png
    - lib/app/assets/images/myket.png
    - lib/app/assets/images/psp.png
    - lib/assets/avatars/1.jpg
    - lib/assets/avatars/2.jpg
    - lib/assets/avatars/3.jpg
    - lib/assets/avatars/4.jpg
    - lib/assets/avatars/5.jpg
    - lib/assets/avatars/6.jpg
    - lib/assets/avatars/7.jpg
    - lib/assets/avatars/8.jpg
    - lib/assets/avatars/9.jpg
    - lib/assets/avatars/10.jpg
    - lib/assets/avatars/11.jpg
    - lib/assets/avatars/12.jpg
    - lib/assets/avatars/13.jpg
