name: chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.6.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  gap: ^3.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  event_bus: ^2.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  crop_image: ^1.0.13
  vibration: ^2.0.0
  flutter_linear_datepicker: ^2.0.6
  shamsi_date: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  # fonts
  fonts:
    - family: YekanBakh
      fonts:
        - asset: lib/assets/fonts/YekanBakhFaNum-Regular.ttf

  # assets
  assets:
    - lib/app/app.env
    - lib/assets/images/empty.png
    - lib/app/assets/images/splash_logo.png
    - lib/app/assets/images/auth_logo.png
    - lib/app/assets/images/auth_hero.png
    - lib/app/assets/images/star.png
